name: Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: test --continue --no-daemon --no-build-cache
